environment:
  access_token:
    secure: XFfVvroKdHjCHRpjPN1VWDMJ0U0gt6ciKzEPK2OYVNjoYMrc9yE97UwtNzi+8vJJ
  iric_appveyor_access_token:
    secure: 55pEdH+k+aocMad2YNOe4QPufbra93mZ2/5mmVRQ2zyjl5/56QsroQdJinyofpo0
  iric_access_token:
    secure: ee8J3ZdtlbFttFmkcumsXr1/FKYOkf/vkN2ZC6lkymz3uOVTs23CXfQS4uMi/zVt
  scharlton2_access_token:
    secure: Kt5VLMSJeqiQyx3Ox3sphU62h9OlWJeiOi7da6DSCuSjv3sp7Ab2LB4m717mCtN2



branches:
  only:
    - master

build_script:
  - ps: Get-Date >> README.md

on_success:
  - git config --global credential.helper store
  - ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:scharlton2_access_token):x-oauth-basic@github.com`n" -NoNewline
  # Note user.email/user.name doesn't have to match access_token
  # if user is not yet a contributer error:
  #   https://ci.appveyor.com/project/scharlton2/apperror/builds/32937996
  - git config --global user.email "iric.appveyor@gmail.com"
  - git config --global user.name "iric.appveyor"
  - git checkout master
  - git checkout -b %APPVEYOR_JOB_ID%
  - git remote -v
  - git commit -am"Testing"
  - git push --set-upstream origin %APPVEYOR_JOB_ID%
