environment:
  access_token:
    secure: XFfVvroKdHjCHRpjPN1VWDMJ0U0gt6ciKzEPK2OYVNjoYMrc9yE97UwtNzi+8vJJ

build_script:
  - ps: Get-Date >> README.md

on_success:
  - git config --global credential.helper store
  - ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - git config --global user.email "charlton@usgs.gov"
  - git config --global user.name "Scott Charlton"
  - git checkout master
  - git remote -v
  - git commit -am"Testing"
  - git push