version: '{branch}-{build}'

image: Visual Studio 2013

# called before clone
# Note that environment variables don't seem to transfer correctly from cmd to ps when
# they contain spaces
init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: $(Get-ChildItem env:)
  - ps: $CommitAndPush = $True

build_script:
  - echo msbuild /nologo /verbosity:minimal src.sln

after_build:
  - ps: |
      if ($CommitAndPush) {
        Write-Output "This is the $env:APPVEYOR_REPO_BRANCH branch"
        $SaveErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = "Stop"
        ## The next line prompts for login credentials and causes appveyor to hang
        ## git clone -q --branch=master https://github.com/scharlton2/XHelloWorld.git
        whoami /aa
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
        # display environment variables
        Get-ChildItem env:
        $ErrorActionPreference = $SaveErrorActionPreference
      }

on_success:
  - echo "on_success"

on_failure:
  - echo "on_failure"

on_finish:
  - echo "on_finish"
