environment:
  access_token:
    secure: XFfVvroKdHjCHRpjPN1VWDMJ0U0gt6ciKzEPK2OYVNjoYMrc9yE97UwtNzi+8vJJ
  iric_appveyor_access_token:
    secure: 55pEdH+k+aocMad2YNOe4QPufbra93mZ2/5mmVRQ2zyjl5/56QsroQdJinyofpo0
  iric_access_token:
    secure: ee8J3ZdtlbFttFmkcumsXr1/FKYOkf/vkN2ZC6lkymz3uOVTs23CXfQS4uMi/zVt
  scharlton2_access_token:
    secure: Kt5VLMSJeqiQyx3Ox3sphU62h9OlWJeiOi7da6DSCuSjv3sp7Ab2LB4m717mCtN2

branches:
  only:
    - master

build_script:
  - ps: Get-Date >> README.md

on_success:
  - ps: |
      if ($True) {
        $access_token = $env:scharlton2_access_token
        git config --global credential.helper store
        Add-Content -Path "$HOME\.git-credentials" -Value "https://$($access_token):x-oauth-basic@github.com`n" -NoNewline -ErrorAction Stop
        # Note user.email/user.name doesn't have to match access_token
        # if user is not yet a contributer error:
        #   https://ci.appveyor.com/project/scharlton2/apperror/builds/32937996
        git config --global user.email "iric.appveyor@gmail.com"
        git config --global user.name "iric.appveyor"
        
        git checkout -q master
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git checkout -qb $env:APPVEYOR_JOB_ID
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git commit -qam"built by iric.appveyor"
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git push --set-upstream origin $env:APPVEYOR_JOB_ID 2>&1 | Out-Null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git status
      }
